arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - link1_j
    - link2_j
    - link3_j
    - link4_j
    - link5_j
  gains:
    link1_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link2_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link3_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link4_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link5_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - grip1_j
    - grip2_j
  gains:
    grip1_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grip2_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1